### ISSUE TITLE
如何固定DataStore.admin_token 的值

### ISSUE THREAD

**Issue by lishuaiyin02** [FiveAourThe/sqlmap_api_demo#1]
博主，你好，我之前还花钱买了你的sqlmap的课程，但是那课程上边的留言一直提交不上去，就找到了这个Git，目前有两个问题想咨询您：
1.如何DataStore.admin_token 的值啊，虽然在代码中找到了对应的这行代码，但是经过几番尝试，还是不能够固定这个值，总是报错，DataStore.admin_token = hexencode(os.urandom(16))，这行代码应该怎么改呢？您能给举个例子吗？
2.如何在客户端中获取到您客户端的这个DataStore.admin_token值呢？sqlmap新手，望您讲解。

**Comment by lishuaiyin02** [comment]
应该是如何获取DataStore.admin_token 的值。

**Comment by lishuaiyin02** [comment]
如何在客户端中获取到您服务端的这个DataStore.admin_token值呢

**Comment by FiveAourThe** [comment]
您好！实在不好意思，长时间没有看Github。首先感谢您购买我的公开课~我这边测试是可以固定的，您可以试试！
`DataStore.admin_token = encodeHex("abcdefghijkmkmxx", binary=False)`

**Comment by lishuaiyin02** [comment]
首先，谢谢您的回复😁。我知道不可以固定的原因了，因为我用记事本改的代码，虽然表面看空格对齐了，但是实际的检查中空格没有对齐，我后来用pycharm改了一下代码发现可以了。
那个客服端有啥办法可以获取服务端的admin_token值吗？谢谢😜
 
---原始邮件---
发件人: "看不尽的尘埃"<notifications@github.com&gt;
发送时间: 2020年3月10日(星期二) 中午12:51
收件人: "FiveAourThe/sqlmap_api_demo"<sqlmap_api_demo@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Shuaiyin Li"<1573551600@qq.com&gt;;
主题: Re: [FiveAourThe/sqlmap_api_demo] 如何固定DataStore.admin_token 的值 (#1)



您好！实在不好意思，长时间没有看Github。首先感谢您购买我的公开课~我这边测试是可以固定的，您可以试试！
 DataStore.admin_token = encodeHex("abcdefghijkmkmxx", binary=False)

**Comment by FiveAourThe** [comment]
> 首先，谢谢您的回复😁。我知道不可以固定的原因了，因为我用记事本改的代码，虽然表面看空格对齐了，但是实际的检查中空格没有对齐，我后来用pycharm改了一下代码发现可以了。 那个客服端有啥办法可以获取服务端的admin_token值吗？谢谢😜
> […](#)
> ---原始邮件--- 发件人: "看不尽的尘埃"<notifications@github.com&gt; 发送时间: 2020年3月10日(星期二) 中午12:51 收件人: "FiveAourThe/sqlmap_api_demo"<sqlmap_api_demo@noreply.github.com&gt;; 抄送: "State change"<state_change@noreply.github.com&gt;;"Shuaiyin Li"<1573551600@qq.com&gt;; 主题: Re: [FiveAourThe/sqlmap_api_demo] 如何固定DataStore.admin_token 的值 (#1) 您好！实在不好意思，长时间没有看Github。首先感谢您购买我的公开课~我这边测试是可以固定的，您可以试试！ DataStore.admin_token = encodeHex("abcdefghijkmkmxx", binary=False) — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

您好，我暂时从源码中没找到客户端获取服务端的admin_token的HTTP路由。

**Comment by lishuaiyin02** [comment]
好的，谢谢回复😄。有问题再向您请教😁


 
---原始邮件---
发件人: "看不尽的尘埃"<notifications@github.com&gt;
发送时间: 2020年3月10日(星期二) 下午4:51
收件人: "FiveAourThe/sqlmap_api_demo"<sqlmap_api_demo@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Shuaiyin Li"<1573551600@qq.com&gt;;
主题: Re: [FiveAourThe/sqlmap_api_demo] 如何固定DataStore.admin_token 的值 (#1)


 
首先，谢谢您的回复😁。我知道不可以固定的原因了，因为我用记事本改的代码，虽然表面看空格对齐了，但是实际的检查中空格没有对齐，我后来用pycharm改了一下代码发现可以了。 那个客服端有啥办法可以获取服务端的admin_token值吗？谢谢😜
 …
 ---原始邮件--- 发件人: "看不尽的尘埃"<notifications@github.com&gt; 发送时间: 2020年3月10日(星期二) 中午12:51 收件人: "FiveAourThe/sqlmap_api_demo"<sqlmap_api_demo@noreply.github.com&gt;; 抄送: "State change"<state_change@noreply.github.com&gt;;"Shuaiyin Li"<1573551600@qq.com&gt;; 主题: Re: [FiveAourThe/sqlmap_api_demo] 如何固定DataStore.admin_token 的值 (#1) 您好！实在不好意思，长时间没有看Github。首先感谢您购买我的公开课~我这边测试是可以固定的，您可以试试！ DataStore.admin_token = encodeHex("abcdefghijkmkmxx", binary=False) — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
  
您好，我暂时从源码中没找到客户端获取服务端的admin_token的HTTP路由。
